---
title: Yavuz Alp Sencer ÖZTÜRK
timezone: UTC
collections:
  news:
    title: News
    output: true
    permalink: "/news/:path/"
    defaults:
      layout: post
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: assets/**/*.*
  values:
    sitemap: false
first_name: Yavuz Alp Sencer
middle_name: 
last_name: ÖZTÜRK
email: alpsencerzozturk@gmail.com
description: "Curious, Computer science enthusiast, Inventor, Explorer, Designer,
  Illusionist \n"
footer_text: ''
keywords: alpsencer, yavuz alp sencer ozturk, bio
lang: en
icon: "\U0001F468‍\U0001F4BB"
url: https://alpsencer.com
baseurl: 
last_updated: true
impressum_path: 
rss_icon: true
navbar_fixed: true
footer_fixed: true
max_width: 800px
serve_og_meta: false
serve_schema_org: false
og_image: 
github_username: alpsencer
gitlab_username: 
twitter_username: alpsencerozturk
linkedin_username: yavuzalpsencerozturk
scholar_userid: 
orcid_id: 
medium_username: 
quora_username: 
publons_id: 
research_gate_profile: 
blogger_url: 
work_url: 
keybase_username: 
wikidata_id: 
dblp_url: 
stackoverflow_id: 
contact_note: 'You can even add a little note about which of these is the best way
  to reach you.

'
google_analytics: 
google_site_verification: 
bing_site_verification: 
panelbear_analytics: 
blog_name: Yavuz Alp Sencer OZTURK
blog_nav_title: blog
blog_description: Projects and life
permalink: "/blog/:year/:title/"
pagination:
  enabled: true
disqus_shortname: al-folio
external_sources:
- name: medium.com
  rss_url: https://medium.com/@alpsencer/feed
news_limit: 5
markdown: kramdown
highlighter: rouge
highlight_theme_light: github
highlight_theme_dark: native
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
include:
- _pages
exclude:
- bin
- Gemfile
- Gemfile.lock
- vendor
keep_files:
- CNAME
- ".nojekyll"
- ".git"
plugins:
- jekyll-archives
- jekyll-diagrams
- jekyll-email-protect
- jekyll-feed
- jekyll-imagemagick
- jekyll-minifier
- jekyll-paginate-v2
- jekyll/scholar
- jekyll-sitemap
- jekyll-target-blank
- jekyll-twitter-plugin
- jemoji
jekyll-minifier:
  exclude:
  - robots.txt
  uglifier_args:
    harmony: true
jekyll-archives:
  enabled:
  - year
  - tags
  - categories
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: "/blog/:year/"
    tag: "/blog/tag/:name/"
    category: "/blog/category/:name/"
scholar:
  last_name: Einstein
  first_name:
  - Albert
  - A.
  style: apa
  locale: en
  source: "/_bibliography/"
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters:
  - latex
  - smallcaps
  - superscript
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"
filtered_bibtex_keywords:
- abbr
- abstract
- arxiv
- bibtex_show
- html
- pdf
- selected
- supp
- blog
- code
- poster
- slides
- website
imagemagick:
  enabled: true
  widths:
  - 480
  - 800
  - 1400
  input_directories:
  - assets/img/
  input_formats:
  - ".jpg"
  - ".jpeg"
  - ".png"
  - ".tiff"
  output_formats:
    webp: "-quality 75%"
jekyll-diagrams: 
enable_google_analytics: false
enable_panelbear_analytics: false
enable_google_verification: false
enable_bing_verification: false
enable_masonry: true
enable_math: true
enable_tooltips: false
enable_darkmode: true
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true
academicons:
  version: 1.9.1
  integrity: sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg=
bootstrap:
  version: 4.6.1
  integrity:
    css: sha256-DF7Zhf293AJxJNTmh5zhoYYIMs2oXitRfBjY+9L//AY=
    js: sha256-SyTu6CwrfOhaznYZPoolVw2rxoY7lKYKQvqbtqN93HI=
fontawesome:
  version: 5.15.4
  integrity: sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4=
jquery:
  version: 3.6.0
  integrity: sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=
mathjax:
  version: 3.2.0
masonry:
  version: 4.2.2
  integrity: sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI=
mdb:
  version: 4.20.0
  integrity:
    css: sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw=
    js: sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA=
popper:
  version: 2.11.2
  integrity: sha256-l/1pMF/+J4TThfgARS6KwWrk/egwuVvhRzfLAMQ6Ds4=
medium_zoom:
  version: 1.0.6
  integrity: sha256-EdPgYcPk/IIrw7FYeuJQexva49pVRZNmt3LculEr7zM=
