# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Steven Kordonowy
email: skordono@ucsc.edu
description: >
  Steven Kordonowy's personal website
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  <a href="https://opensource.org/licenses/MIT" target="_blank">MIT</a> license.

url:  # the base hostname & protocol for your site
baseurl: #/al-folio # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated


# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# To achieve this, change serve_og_meta to true and then provide the URL of the
# preview image as the value of og_image.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image
# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: stevenkordonowy # your GitHub user name
twitter_username: # your Twitter handle
linkedin_username: steven-kordonowy-52a7648a # your LinkedIn user name
scholar_userid: # your Google Scholar ID
orcid_id: # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
blogger_url: # your blogger URL
discogs: https://www.discogs.com/user/sakattack
goodreads: https://www.goodreads.com/user/show/49692865-steven-kordonowy

contact_note: >
  I respond fastest to emails!

google_analytics: UA-XXXXXXXXX # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
# blog_name: al-folio
# blog_description: a simple whitespace theme for academics

# Pagination
# paginate: 4
# permalink: /blog/:year/:title/
# paginate_path: /blog/page:num/

# text:
#   pagination:
#     newer: 'Newer'
#     older: 'Older'

# # Comments
# disqus_shortname: al-folio # put your disqus shortname

# # Optional features
# show_social_icons:  false
# enable_anchorjs:    false
# enable_katex:       true

research:
  - project:
    title: ''
    description: 'Comparing classical and quantum FLIP algorithms for the local max-cut problem. [preprint](https://arxiv.org/abs/2304.08420)'
    collaborators:
      - 
        name: Alex Kolla
        site: https://people.ucsc.edu/~akolla/
      -
        name: Charles Carlson
        site: www.charlieintheory.com
      -
        name: Zack Jorquera
        site: https://zackjorquera.github.io/
    link: 
      filename: qip-2021-poster.pdf
      title: QIP 2021 Poster
  - project:
    title: 'Approximating the quantum extension of Max-k-Cut'
    description: 'Extending results on quantum max-cut to k-level quantum systems mirroring the extension from max-cut to max-k-cut.'
    collaborators:
      - 
        name: Alex Kolla
        site: https://home.cs.colorado.edu/~alko5368/
      -
        name: Charles Carlson
        site: https://cacarlson.github.io/
    
  - project:
    title: 'A quantum evolutionary algorithm for max-cut (Spring 2020). Written for a class CSCI 5423 Bio-inspired Multi Agent Systems'
    description: '[Github repo](https://github.com/stevenkordonowy/qea-max-cut)'

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Einstein

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
