# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.13.2
    build: .
    # uncomment these if you are having this issue with the build:
    # /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/site.rb:509:in `initialize': Permission denied @ rb_sysopen - /srv/jekyll/.jekyll-cache/.gitignore (Errno::EACCES)
    # and fill the args values with the output of the commands on the right
    # build:
    #   args:
    #     GROUPID: # id -g
    #     GROUPNAME: # id -gn
    #     USERID: # id -u
    #     USERNAME: # echo $USER
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
