version: '2'
services:
  site:
    environment:
      - JEKYLL_ENV=production
    command: jekyll serve --watch --force_polling --config  _config.yml,_config.docker.yml
    image: dgraziotin/jekyll-imagemagick6:stable
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
