language: ruby

sudo: false
cache: bundler

matrix:
  fast_finish: true
  include:
  - rvm: 2.5
    env: WITH_COVERALLS=true
  - rvm: 2.4
    env: WITH_COVERALLS=false
  - rvm: 2.3
    env: WITH_COVERALLS=false
  - rvm: 2.2
    env: WITH_COVERALLS=false
  - rvm: jruby-19mode
    env: WITH_COVERALLS=false

install:
  - if [[ $WITH_COVERALLS = "true" ]]; then
      bundle install --without debug optional;
    else
      bundle install --without debug optional coverage;
    fi

script:
  - if [[ $WITH_COVERALLS = "true" ]]; then
      bundle exec rake test_with_coveralls;
    else
      bundle exec rake;
    fi

notifications:
  email: false
