# for details on settings, see https://docs.rendercv.com/user_guide/yaml_input_structure/settings/
settings:
  render_command:
    # Paths must be relative to _data/cv.yaml
    design: ../assets/rendercv/design.yaml
    locale: ../assets/rendercv/locale.yaml
    typst_path: ../assets/rendercv/rendercv_output/NAME_IN_SNAKE_CASE_CV.typ
    pdf_path: ../assets/rendercv/rendercv_output/NAME_IN_SNAKE_CASE_CV.pdf
    markdown_path: ../assets/rendercv/rendercv_output/NAME_IN_SNAKE_CASE_CV.md
    html_path: ../assets/rendercv/rendercv_output/NAME_IN_SNAKE_CASE_CV.html
    png_path: ../assets/rendercv/rendercv_output/NAME_IN_SNAKE_CASE_CV.png
    dont_generate_markdown: true
    dont_generate_html: true
    dont_generate_typst: false # typst generation is required for pdf output
    dont_generate_pdf: false
    dont_generate_png: true
  bold_keywords: []
