settings:
  render_command:
    design:
    locale:
    # Paths must be relative to _data/cv.yaml
    typst_path: ../assets/rendercv/rendercv_output/NAME_IN_SNAKE_CASE_CV.typ
    pdf_path: ../assets/rendercv/rendercv_output/NAME_IN_SNAKE_CASE_CV.pdf
    markdown_path: ../assets/rendercv/rendercv_output/NAME_IN_SNAKE_CASE_CV.md
    html_path: ../assets/rendercv/rendercv_output/NAME_IN_SNAKE_CASE_CV.html
    png_path: ../assets/rendercv/rendercv_output/NAME_IN_SNAKE_CASE_CV.png
    dont_generate_markdown: true
    dont_generate_html: true
    dont_generate_typst: false
    dont_generate_pdf: false
    dont_generate_png: true
  bold_keywords: []
