name: Validate CV.yml

on:
  push:
    branches:
      - master
      - main
    paths:
      - "_data/cv.yml"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "_data/cv.yml"
  workflow_dispatch:

jobs:
  validate_cv:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Validate cv.yml ğŸ§ª
        uses: cardinalby/schema-validator-action@v3
        with:
          file: "_data/cv.yml|_data/cv_design.yaml|_data/cv_locale.yaml"
          mode: "lax"
          schema: "rendercv-schema.json"
          fixSchemas: true
