name: Get Pagespeed results
on:
  # schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron:  '0 0 * * *' # 00:00 UTC
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  getpsresults:
    env:
      HOST: https://alshedivat.github.io/al-folio/
      PSURL: https://pagespeed-insights.herokuapp.com
      PSRDESKTOP: psresultdesktop
      PSRMOBILE: psresultmobile
      RESULTSFOLDER: reports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # This is a premade github action
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: | # Have to be sure a folder is present if not, make it
          mkdir -p ${RESULTSFOLDER}
          curl "${PSURL}/?url=${HOST}" > ./${RESULTSFOLDER}/${PSRDESKTOP}.svg
          curl "${PSURL}/?url=${HOST}&strategy=mobile" > ./${RESULTSFOLDER}/${PSRMOBILE}.svg
    - name: Commit files
      run: |
        git add .
        git config --local user.email "actions@github.com"
        git config --local user.name "github-actions[bot]"
        git diff --quiet && git diff --staged --quiet || git commit -am "Updated Pagespeed results"
    - name: Push changes
      uses: ad-m/github-push-action@master # This is a premade github action
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}